// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitOfWork;

#nullable disable

namespace UnitOfWork.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240515175910_CreateGrammarTopicTable")]
    partial class CreateGrammarTopicTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.AiMessage", b =>
                {
                    b.Property<int>("AiMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AiMessageId"));

                    b.Property<int>("EssayId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AiMessageId");

                    b.HasIndex("EssayId");

                    b.ToTable("AiMessages");
                });

            modelBuilder.Entity("DbModels.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AuthorName = "Edgar Allan Poe"
                        },
                        new
                        {
                            AuthorId = 2,
                            AuthorName = "O.Henry"
                        },
                        new
                        {
                            AuthorId = 3,
                            AuthorName = "Ernest Hemingway"
                        },
                        new
                        {
                            AuthorId = 4,
                            AuthorName = "F.Scott Fitzgerald"
                        },
                        new
                        {
                            AuthorId = 5,
                            AuthorName = "Alice Munro"
                        },
                        new
                        {
                            AuthorId = 6,
                            AuthorName = "Jorge Luis Borges"
                        },
                        new
                        {
                            AuthorId = 7,
                            AuthorName = "Guy de Maupassant"
                        },
                        new
                        {
                            AuthorId = 8,
                            AuthorName = "Ray Bradbury"
                        },
                        new
                        {
                            AuthorId = 9,
                            AuthorName = "Flannery O'Connor"
                        },
                        new
                        {
                            AuthorId = 10,
                            AuthorName = "Shirley Jackson"
                        },
                        new
                        {
                            AuthorId = 11,
                            AuthorName = "Haruki Murakami"
                        },
                        new
                        {
                            AuthorId = 12,
                            AuthorName = "Jules Verne"
                        },
                        new
                        {
                            AuthorId = 13,
                            AuthorName = "Mark Twain"
                        },
                        new
                        {
                            AuthorId = 14,
                            AuthorName = "Stephen King"
                        },
                        new
                        {
                            AuthorId = 15,
                            AuthorName = "John Cheever"
                        },
                        new
                        {
                            AuthorId = 16,
                            AuthorName = "Isaac Asimov"
                        },
                        new
                        {
                            AuthorId = 17,
                            AuthorName = "James Joyce"
                        },
                        new
                        {
                            AuthorId = 18,
                            AuthorName = "Nathaniel Hawthorne"
                        },
                        new
                        {
                            AuthorId = 19,
                            AuthorName = "H.P.Lovecraft"
                        },
                        new
                        {
                            AuthorId = 20,
                            AuthorName = "Virginia Woolf"
                        },
                        new
                        {
                            AuthorId = 21,
                            AuthorName = "William Faulkner"
                        },
                        new
                        {
                            AuthorId = 22,
                            AuthorName = "Eudora Welty"
                        },
                        new
                        {
                            AuthorId = 23,
                            AuthorName = "Katherine Mansfield"
                        },
                        new
                        {
                            AuthorId = 24,
                            AuthorName = "Kurt Vonnegut"
                        },
                        new
                        {
                            AuthorId = 25,
                            AuthorName = "Philip K.Dick"
                        },
                        new
                        {
                            AuthorId = 26,
                            AuthorName = "Charles Bukowski"
                        },
                        new
                        {
                            AuthorId = 27,
                            AuthorName = "Roald Dahl"
                        },
                        new
                        {
                            AuthorId = 28,
                            AuthorName = "Henry James"
                        },
                        new
                        {
                            AuthorId = 29,
                            AuthorName = "Edgar Rice Burroughs"
                        },
                        new
                        {
                            AuthorId = 30,
                            AuthorName = "Truman Capote"
                        });
                });

            modelBuilder.Entity("DbModels.Dictionary", b =>
                {
                    b.Property<int>("DictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DictionaryId"));

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("DictionaryId");

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("DbModels.Essay", b =>
                {
                    b.Property<int>("EssayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EssayId"));

                    b.Property<string>("BriefText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EssayId");

                    b.ToTable("Essays");
                });

            modelBuilder.Entity("DbModels.GrammarTopic", b =>
                {
                    b.Property<int>("GrammarTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrammarTopicId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageLevelId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("GrammarTopicId");

                    b.HasIndex("LanguageLevelId");

                    b.ToTable("GrammarTopics");

                    b.HasData(
                        new
                        {
                            GrammarTopicId = 1,
                            Description = "For habitual actions and daily routines",
                            LanguageLevelId = 2,
                            Order = 1,
                            Text = "Present Simple Tense"
                        },
                        new
                        {
                            GrammarTopicId = 2,
                            Description = "For actions happening at the moment of speaking",
                            LanguageLevelId = 2,
                            Order = 2,
                            Text = "Present Continuous Tense"
                        },
                        new
                        {
                            GrammarTopicId = 3,
                            Description = "To talk about completed actions in the past",
                            LanguageLevelId = 2,
                            Order = 3,
                            Text = "Past Simple Tense"
                        },
                        new
                        {
                            GrammarTopicId = 4,
                            Description = "For planned actions or intentions",
                            LanguageLevelId = 2,
                            Order = 4,
                            Text = "Future with 'going to'"
                        },
                        new
                        {
                            GrammarTopicId = 5,
                            Description = "To express ability or possibility",
                            LanguageLevelId = 2,
                            Order = 5,
                            Text = "Can/Could for Ability"
                        },
                        new
                        {
                            GrammarTopicId = 6,
                            Description = "To compare things and people",
                            LanguageLevelId = 2,
                            Order = 6,
                            Text = "Comparatives and Superlatives"
                        },
                        new
                        {
                            GrammarTopicId = 7,
                            Description = "Such as 'in', 'at', 'on' for describing time",
                            LanguageLevelId = 2,
                            Order = 7,
                            Text = "Prepositions of Time"
                        },
                        new
                        {
                            GrammarTopicId = 8,
                            Description = "Such as 'in', 'at', 'on' for describing location",
                            LanguageLevelId = 2,
                            Order = 8,
                            Text = "Prepositions of Place"
                        },
                        new
                        {
                            GrammarTopicId = 9,
                            Description = "Such as 'must', 'should' for necessity and advice",
                            LanguageLevelId = 2,
                            Order = 9,
                            Text = "Simple Modal Verbs"
                        },
                        new
                        {
                            GrammarTopicId = 10,
                            Description = "Using 's and s' to show possession",
                            LanguageLevelId = 2,
                            Order = 10,
                            Text = "Possessives"
                        },
                        new
                        {
                            GrammarTopicId = 11,
                            Description = "Including use of 'some' and 'any'",
                            LanguageLevelId = 2,
                            Order = 11,
                            Text = "Countable and Uncountable Nouns"
                        },
                        new
                        {
                            GrammarTopicId = 12,
                            Description = "Such as 'always', 'usually', 'often', 'sometimes', 'never'",
                            LanguageLevelId = 2,
                            Order = 12,
                            Text = "Adverbs of Frequency"
                        },
                        new
                        {
                            GrammarTopicId = 13,
                            Description = "To describe the existence or presence of something",
                            LanguageLevelId = 2,
                            Order = 13,
                            Text = "There is/There are"
                        },
                        new
                        {
                            GrammarTopicId = 14,
                            Description = "For giving direct orders and requests",
                            LanguageLevelId = 2,
                            Order = 14,
                            Text = "Imperatives"
                        },
                        new
                        {
                            GrammarTopicId = 15,
                            Description = "For actions that were in progress at a specific time in the past",
                            LanguageLevelId = 2,
                            Order = 15,
                            Text = "Past Continuous Tense"
                        });
                });

            modelBuilder.Entity("DbModels.LanguageLevel", b =>
                {
                    b.Property<int>("LanguageLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageLevelId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LanguageLevelId");

                    b.ToTable("LanguageLevels");

                    b.HasData(
                        new
                        {
                            LanguageLevelId = 1,
                            Code = "A1",
                            Description = "Can understand and use familiar everyday expressions and very basic phrases aimed at the satisfaction of needs of a concrete type.\r\nCan introduce themselves and others and can ask and answer questions about personal details such as where they live, people they know, and things they have.\r\nCan interact in a simple way provided the other person talks slowly and clearly and is prepared to help.",
                            Name = "Beginner"
                        },
                        new
                        {
                            LanguageLevelId = 2,
                            Code = "A2",
                            Description = "Can understand sentences and frequently used expressions related to areas of most immediate relevance (e.g., very basic personal and family information, shopping, local geography, employment).\r\nCan communicate in simple and routine tasks requiring a simple and direct exchange of information on familiar and routine matters.\r\nCan describe in simple terms aspects of their background, immediate environment, and matters in areas of immediate need.",
                            Name = "Elementary"
                        },
                        new
                        {
                            LanguageLevelId = 3,
                            Code = "B1",
                            Description = "Can understand the main points of clear standard input on familiar matters regularly encountered in work, school, leisure, etc.\r\nCan deal with most situations likely to arise while traveling in an area where the language is spoken.\r\nCan produce simple connected text on topics that are familiar or of personal interest.\r\nCan describe experiences and events, dreams, hopes, and ambitions and briefly give reasons and explanations for opinions and plans.",
                            Name = "Intermediate"
                        },
                        new
                        {
                            LanguageLevelId = 4,
                            Code = "B2",
                            Description = "Can understand the main ideas of complex text on both concrete and abstract topics, including technical discussions in their field of specialization.\r\nCan interact with a degree of fluency and spontaneity that makes regular interaction with native speakers quite possible without strain for either party.\r\nCan produce clear, detailed text on a wide range of subjects and explain a viewpoint on a topical issue giving the advantages and disadvantages of various options.",
                            Name = "Upper Intermediate"
                        },
                        new
                        {
                            LanguageLevelId = 5,
                            Code = "C1",
                            Description = "Can understand a wide range of demanding, longer texts, and recognize implicit meaning.\r\nCan express ideas fluently and spontaneously without much obvious searching for expressions.\r\nCan use language flexibly and effectively for social, academic, and professional purposes.\r\nCan produce clear, well-structured, detailed text on complex subjects, showing controlled use of organizational patterns, connectors, and cohesive devices.",
                            Name = "Advanced"
                        },
                        new
                        {
                            LanguageLevelId = 6,
                            Code = "C2",
                            Description = "Can understand with ease virtually everything heard or read.\r\nCan summarize information from different spoken and written sources, reconstructing arguments and accounts in a coherent presentation.\r\nCan express themselves spontaneously, very fluently and precisely, differentiating finer shades of meaning even in more complex situations.",
                            Name = "Proficiency"
                        });
                });

            modelBuilder.Entity("DbModels.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("StoryId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("DbModels.StoryParagraph", b =>
                {
                    b.Property<int>("StoryParagraphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryParagraphId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoryParagraphId");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryParagraphs");
                });

            modelBuilder.Entity("DbModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "4ee84463-8487-44e6-8e9f-9ba6542b0465",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6788ae54-071c-4f5b-aed1-986160666db0",
                            Email = "SuperAdmin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9aaf4bd7-baa3-4b51-a1ea-1dfb5e0f8565",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("DbModels.AiMessage", b =>
                {
                    b.HasOne("DbModels.Essay", "Essay")
                        .WithMany("AiMessages")
                        .HasForeignKey("EssayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Essay");
                });

            modelBuilder.Entity("DbModels.GrammarTopic", b =>
                {
                    b.HasOne("DbModels.LanguageLevel", "LanguageLevel")
                        .WithMany()
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageLevel");
                });

            modelBuilder.Entity("DbModels.StoryParagraph", b =>
                {
                    b.HasOne("DbModels.Story", "Story")
                        .WithMany("Paragraphs")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DbModels.Essay", b =>
                {
                    b.Navigation("AiMessages");
                });

            modelBuilder.Entity("DbModels.Story", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
