// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnitOfWork;

#nullable disable

namespace UnitOfWork.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbModels.AiMessage", b =>
                {
                    b.Property<int>("AiMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AiMessageId"));

                    b.Property<int>("EssayId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AiMessageId");

                    b.HasIndex("EssayId");

                    b.ToTable("AiMessages");
                });

            modelBuilder.Entity("DbModels.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AuthorName = "Edgar Allan Poe"
                        },
                        new
                        {
                            AuthorId = 2,
                            AuthorName = "O.Henry"
                        },
                        new
                        {
                            AuthorId = 3,
                            AuthorName = "Ernest Hemingway"
                        },
                        new
                        {
                            AuthorId = 4,
                            AuthorName = "F.Scott Fitzgerald"
                        },
                        new
                        {
                            AuthorId = 5,
                            AuthorName = "Alice Munro"
                        },
                        new
                        {
                            AuthorId = 6,
                            AuthorName = "Jorge Luis Borges"
                        },
                        new
                        {
                            AuthorId = 7,
                            AuthorName = "Guy de Maupassant"
                        },
                        new
                        {
                            AuthorId = 8,
                            AuthorName = "Ray Bradbury"
                        },
                        new
                        {
                            AuthorId = 9,
                            AuthorName = "Flannery O'Connor"
                        },
                        new
                        {
                            AuthorId = 10,
                            AuthorName = "Shirley Jackson"
                        },
                        new
                        {
                            AuthorId = 11,
                            AuthorName = "Haruki Murakami"
                        },
                        new
                        {
                            AuthorId = 12,
                            AuthorName = "Jules Verne"
                        },
                        new
                        {
                            AuthorId = 13,
                            AuthorName = "Mark Twain"
                        },
                        new
                        {
                            AuthorId = 14,
                            AuthorName = "Stephen King"
                        },
                        new
                        {
                            AuthorId = 15,
                            AuthorName = "John Cheever"
                        },
                        new
                        {
                            AuthorId = 16,
                            AuthorName = "Isaac Asimov"
                        },
                        new
                        {
                            AuthorId = 17,
                            AuthorName = "James Joyce"
                        },
                        new
                        {
                            AuthorId = 18,
                            AuthorName = "Nathaniel Hawthorne"
                        },
                        new
                        {
                            AuthorId = 19,
                            AuthorName = "H.P.Lovecraft"
                        },
                        new
                        {
                            AuthorId = 20,
                            AuthorName = "Virginia Woolf"
                        },
                        new
                        {
                            AuthorId = 21,
                            AuthorName = "William Faulkner"
                        },
                        new
                        {
                            AuthorId = 22,
                            AuthorName = "Eudora Welty"
                        },
                        new
                        {
                            AuthorId = 23,
                            AuthorName = "Katherine Mansfield"
                        },
                        new
                        {
                            AuthorId = 24,
                            AuthorName = "Kurt Vonnegut"
                        },
                        new
                        {
                            AuthorId = 25,
                            AuthorName = "Philip K.Dick"
                        },
                        new
                        {
                            AuthorId = 26,
                            AuthorName = "Charles Bukowski"
                        },
                        new
                        {
                            AuthorId = 27,
                            AuthorName = "Roald Dahl"
                        },
                        new
                        {
                            AuthorId = 28,
                            AuthorName = "Henry James"
                        },
                        new
                        {
                            AuthorId = 29,
                            AuthorName = "Edgar Rice Burroughs"
                        },
                        new
                        {
                            AuthorId = 30,
                            AuthorName = "Truman Capote"
                        });
                });

            modelBuilder.Entity("DbModels.Dictionary", b =>
                {
                    b.Property<int>("DictionaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DictionaryId"));

                    b.Property<string>("Examples")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Transcript")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("DictionaryId");

                    b.ToTable("Dictionaries");
                });

            modelBuilder.Entity("DbModels.Essay", b =>
                {
                    b.Property<int>("EssayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EssayId"));

                    b.Property<string>("BriefText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EssayId");

                    b.ToTable("Essays");
                });

            modelBuilder.Entity("DbModels.GrammarTopic", b =>
                {
                    b.Property<int>("GrammarTopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrammarTopicId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageLevelId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.HasKey("GrammarTopicId");

                    b.HasIndex("LanguageLevelId");

                    b.ToTable("GrammarTopics");

                    b.HasData(
                        new
                        {
                            GrammarTopicId = 1,
                            Description = "For habitual actions and daily routines",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 1,
                            Text = "Present Simple Tense"
                        },
                        new
                        {
                            GrammarTopicId = 2,
                            Description = "For actions happening at the moment of speaking",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 2,
                            Text = "Present Continuous Tense"
                        },
                        new
                        {
                            GrammarTopicId = 3,
                            Description = "To talk about completed actions in the past",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 3,
                            Text = "Past Simple Tense"
                        },
                        new
                        {
                            GrammarTopicId = 4,
                            Description = "For planned actions or intentions",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 4,
                            Text = "Future with 'going to'"
                        },
                        new
                        {
                            GrammarTopicId = 5,
                            Description = "To express ability or possibility",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 5,
                            Text = "Can/Could for Ability"
                        },
                        new
                        {
                            GrammarTopicId = 6,
                            Description = "To compare things and people",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 6,
                            Text = "Comparatives and Superlatives"
                        },
                        new
                        {
                            GrammarTopicId = 7,
                            Description = "Such as 'in', 'at', 'on' for describing time",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 7,
                            Text = "Prepositions of Time"
                        },
                        new
                        {
                            GrammarTopicId = 8,
                            Description = "Such as 'in', 'at', 'on' for describing location",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 8,
                            Text = "Prepositions of Place"
                        },
                        new
                        {
                            GrammarTopicId = 9,
                            Description = "Such as 'must', 'should' for necessity and advice",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 9,
                            Text = "Simple Modal Verbs"
                        },
                        new
                        {
                            GrammarTopicId = 10,
                            Description = "Using 's and s' to show possession",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 10,
                            Text = "Possessives"
                        },
                        new
                        {
                            GrammarTopicId = 11,
                            Description = "Including use of 'some' and 'any'",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 11,
                            Text = "Countable and Uncountable Nouns"
                        },
                        new
                        {
                            GrammarTopicId = 12,
                            Description = "Such as 'always', 'usually', 'often', 'sometimes', 'never'",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 12,
                            Text = "Adverbs of Frequency"
                        },
                        new
                        {
                            GrammarTopicId = 13,
                            Description = "To describe the existence or presence of something",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 13,
                            Text = "There is/There are"
                        },
                        new
                        {
                            GrammarTopicId = 14,
                            Description = "For giving direct orders and requests",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 14,
                            Text = "Imperatives"
                        },
                        new
                        {
                            GrammarTopicId = 15,
                            Description = "For actions that were in progress at a specific time in the past",
                            Explanation = "",
                            LanguageLevelId = 2,
                            Order = 15,
                            Text = "Past Continuous Tense"
                        },
                        new
                        {
                            GrammarTopicId = 16,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 1,
                            Text = "Alphabet and Pronunciation"
                        },
                        new
                        {
                            GrammarTopicId = 17,
                            Description = "Subject-Verb-Object",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 2,
                            Text = "Basic Sentence Structure"
                        },
                        new
                        {
                            GrammarTopicId = 18,
                            Description = "Present Simple",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 3,
                            Text = "To Be"
                        },
                        new
                        {
                            GrammarTopicId = 19,
                            Description = "a, an, the",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 4,
                            Text = "Articles"
                        },
                        new
                        {
                            GrammarTopicId = 20,
                            Description = "I, you, he, she, it, we, they",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 5,
                            Text = "Personal Pronouns"
                        },
                        new
                        {
                            GrammarTopicId = 21,
                            Description = "my, your, his, her, its, our, their",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 6,
                            Text = "Possessive Adjectives"
                        },
                        new
                        {
                            GrammarTopicId = 22,
                            Description = "Affirmative, Negative, Questions",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 7,
                            Text = "Simple Present Tense"
                        },
                        new
                        {
                            GrammarTopicId = 23,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 8,
                            Text = "Common Adjectives"
                        },
                        new
                        {
                            GrammarTopicId = 24,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 9,
                            Text = "Imperatives"
                        },
                        new
                        {
                            GrammarTopicId = 25,
                            Description = "Regular and Irregular",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 10,
                            Text = "Plurals"
                        },
                        new
                        {
                            GrammarTopicId = 26,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 11,
                            Text = "There is / There are"
                        },
                        new
                        {
                            GrammarTopicId = 27,
                            Description = "in, on, under, next to, etc.",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 12,
                            Text = "Prepositions of Place"
                        },
                        new
                        {
                            GrammarTopicId = 28,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 13,
                            Text = "Possessive 's"
                        },
                        new
                        {
                            GrammarTopicId = 29,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 14,
                            Text = "Can for Ability"
                        },
                        new
                        {
                            GrammarTopicId = 30,
                            Description = "Affirmative, Negative, Questions",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 15,
                            Text = "Present Continuous Tense"
                        },
                        new
                        {
                            GrammarTopicId = 31,
                            Description = "who, what, where, when, why, how",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 16,
                            Text = "Question Words"
                        },
                        new
                        {
                            GrammarTopicId = 32,
                            Description = "always, usually, sometimes, never",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 17,
                            Text = "Basic Adverbs of Frequency"
                        },
                        new
                        {
                            GrammarTopicId = 33,
                            Description = "and, but, or",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 18,
                            Text = "Basic Conjunctions"
                        },
                        new
                        {
                            GrammarTopicId = 34,
                            Description = "this, that, these, those",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 19,
                            Text = "Demonstratives"
                        },
                        new
                        {
                            GrammarTopicId = 35,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 1,
                            Order = 20,
                            Text = "Modal Verb 'Would like' for Polite Requests"
                        },
                        new
                        {
                            GrammarTopicId = 36,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 1,
                            Text = "Present Perfect Tense"
                        },
                        new
                        {
                            GrammarTopicId = 37,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 2,
                            Text = "Present Perfect Continuous Tense"
                        },
                        new
                        {
                            GrammarTopicId = 38,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 3,
                            Text = "Past Perfect Tense"
                        },
                        new
                        {
                            GrammarTopicId = 39,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 4,
                            Text = "Past Perfect Continuous Tense"
                        },
                        new
                        {
                            GrammarTopicId = 40,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 5,
                            Text = "Future Continuous Tense"
                        },
                        new
                        {
                            GrammarTopicId = 41,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 6,
                            Text = "Future Perfect Tense"
                        },
                        new
                        {
                            GrammarTopicId = 42,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 7,
                            Text = "Future Perfect Continuous Tense"
                        },
                        new
                        {
                            GrammarTopicId = 43,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 8,
                            Text = "Conditionals (First, Second, Third)"
                        },
                        new
                        {
                            GrammarTopicId = 44,
                            Description = "Express wishes and regrets.",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 9,
                            Text = "Wish/If only"
                        },
                        new
                        {
                            GrammarTopicId = 45,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 10,
                            Text = "Reported Speech"
                        },
                        new
                        {
                            GrammarTopicId = 46,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 11,
                            Text = "Relative Clauses"
                        },
                        new
                        {
                            GrammarTopicId = 47,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 12,
                            Text = "Passive Voice"
                        },
                        new
                        {
                            GrammarTopicId = 48,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 13,
                            Text = "Gerunds and Infinitives"
                        },
                        new
                        {
                            GrammarTopicId = 49,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 14,
                            Text = "Modals of Deduction and Speculation"
                        },
                        new
                        {
                            GrammarTopicId = 50,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 15,
                            Text = "Modals of Obligation and Necessity"
                        },
                        new
                        {
                            GrammarTopicId = 51,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 16,
                            Text = "Phrasal Verbs"
                        },
                        new
                        {
                            GrammarTopicId = 52,
                            Description = "much, many, a lot of, few, little",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 17,
                            Text = "Quantifiers"
                        },
                        new
                        {
                            GrammarTopicId = 53,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 18,
                            Text = "Adjectives and Adverbs"
                        },
                        new
                        {
                            GrammarTopicId = 54,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 19,
                            Text = "Comparatives and Superlatives"
                        },
                        new
                        {
                            GrammarTopicId = 55,
                            Description = "although, despite, in spite of",
                            Explanation = "",
                            LanguageLevelId = 3,
                            Order = 20,
                            Text = "Linking Words"
                        },
                        new
                        {
                            GrammarTopicId = 56,
                            Description = "A comprehensive review of all tenses.",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 1,
                            Text = "Advanced Tenses Review"
                        },
                        new
                        {
                            GrammarTopicId = 57,
                            Description = "Zero, First, Second, Third, Mixed",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 2,
                            Text = "Conditionals"
                        },
                        new
                        {
                            GrammarTopicId = 58,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 3,
                            Text = "Passive Voice"
                        },
                        new
                        {
                            GrammarTopicId = 59,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 4,
                            Text = "Causative Form"
                        },
                        new
                        {
                            GrammarTopicId = 60,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 5,
                            Text = "Reported Speech"
                        },
                        new
                        {
                            GrammarTopicId = 61,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 6,
                            Text = "Relative Clauses"
                        },
                        new
                        {
                            GrammarTopicId = 62,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 7,
                            Text = "Modals of Probability and Speculation"
                        },
                        new
                        {
                            GrammarTopicId = 63,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 8,
                            Text = "Modals of Advice and Suggestions"
                        },
                        new
                        {
                            GrammarTopicId = 64,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 9,
                            Text = "Inversion for Emphasis"
                        },
                        new
                        {
                            GrammarTopicId = 65,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 10,
                            Text = "Future Perfect and Future Continuous"
                        },
                        new
                        {
                            GrammarTopicId = 66,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 11,
                            Text = "Gerunds and Infinitives"
                        },
                        new
                        {
                            GrammarTopicId = 67,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 12,
                            Text = "Phrasal Verbs"
                        },
                        new
                        {
                            GrammarTopicId = 68,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 13,
                            Text = "Hypothetical Situations"
                        },
                        new
                        {
                            GrammarTopicId = 69,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 14,
                            Text = "Mixed Conditionals"
                        },
                        new
                        {
                            GrammarTopicId = 70,
                            Description = "Advanced. Expressing wishes and regrets in complex sentences",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 15,
                            Text = "Wish/If only"
                        },
                        new
                        {
                            GrammarTopicId = 71,
                            Description = "Various idiomatic",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 16,
                            Text = "Expressions with Get"
                        },
                        new
                        {
                            GrammarTopicId = 72,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 17,
                            Text = "Collocations and Fixed Expressions"
                        },
                        new
                        {
                            GrammarTopicId = 73,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 18,
                            Text = "Comparatives and Superlatives"
                        },
                        new
                        {
                            GrammarTopicId = 74,
                            Description = "Turning verbs and adjectives into nouns",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 19,
                            Text = "Nominalization"
                        },
                        new
                        {
                            GrammarTopicId = 75,
                            Description = "Words and phrases for organizing spoken and written language",
                            Explanation = "",
                            LanguageLevelId = 4,
                            Order = 20,
                            Text = "Discourse Markers"
                        },
                        new
                        {
                            GrammarTopicId = 76,
                            Description = "The nuances of different tenses",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 1,
                            Text = "Advanced Tense Usage"
                        },
                        new
                        {
                            GrammarTopicId = 77,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 2,
                            Text = "Subjunctive Mood"
                        },
                        new
                        {
                            GrammarTopicId = 78,
                            Description = "Complex forms of passive voice",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 3,
                            Text = "Advanced Passive Structures"
                        },
                        new
                        {
                            GrammarTopicId = 79,
                            Description = "Using past tenses for storytelling",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 4,
                            Text = "Narrative Tenses"
                        },
                        new
                        {
                            GrammarTopicId = 80,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 5,
                            Text = "Cleft Sentences"
                        },
                        new
                        {
                            GrammarTopicId = 81,
                            Description = "Complex relative clauses for adding detailed information.",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 6,
                            Text = "Relative Clauses"
                        },
                        new
                        {
                            GrammarTopicId = 82,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 7,
                            Text = "Conditionals"
                        },
                        new
                        {
                            GrammarTopicId = 83,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 8,
                            Text = "Inversion for Emphasis"
                        },
                        new
                        {
                            GrammarTopicId = 84,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 9,
                            Text = "Ellipsis and Substitution"
                        },
                        new
                        {
                            GrammarTopicId = 85,
                            Description = "Reporting complex statements, questions, and commands.",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 10,
                            Text = "Reported Speech"
                        },
                        new
                        {
                            GrammarTopicId = 86,
                            Description = "Modals for past deductions, regrets, and speculation.",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 11,
                            Text = "Modals in Past Forms"
                        },
                        new
                        {
                            GrammarTopicId = 87,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 12,
                            Text = "Complex Sentence Structures"
                        },
                        new
                        {
                            GrammarTopicId = 88,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 13,
                            Text = "Advanced Phrasal Verbs and Idioms"
                        },
                        new
                        {
                            GrammarTopicId = 89,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 14,
                            Text = "Hedging Language"
                        },
                        new
                        {
                            GrammarTopicId = 90,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 15,
                            Text = "Nominalization"
                        },
                        new
                        {
                            GrammarTopicId = 91,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 16,
                            Text = "Parallel Structures"
                        },
                        new
                        {
                            GrammarTopicId = 92,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 17,
                            Text = "Discourse Markers"
                        },
                        new
                        {
                            GrammarTopicId = 93,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 18,
                            Text = "Relative Pronouns and Adverbs"
                        },
                        new
                        {
                            GrammarTopicId = 94,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 19,
                            Text = "Degrees of Certainty"
                        },
                        new
                        {
                            GrammarTopicId = 95,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 5,
                            Order = 20,
                            Text = "Complex Quantifiers"
                        },
                        new
                        {
                            GrammarTopicId = 96,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 1,
                            Text = "Subjunctive Mood"
                        },
                        new
                        {
                            GrammarTopicId = 97,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 2,
                            Text = "Advanced Conditional Structures"
                        },
                        new
                        {
                            GrammarTopicId = 98,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 3,
                            Text = "Inversion in Conditional Sentences"
                        },
                        new
                        {
                            GrammarTopicId = 99,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 4,
                            Text = "Advanced Passive Constructions"
                        },
                        new
                        {
                            GrammarTopicId = 100,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 5,
                            Text = "Ellipsis and Substitution"
                        },
                        new
                        {
                            GrammarTopicId = 101,
                            Description = "Advanced",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 6,
                            Text = "Cleft Sentences"
                        },
                        new
                        {
                            GrammarTopicId = 102,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 7,
                            Text = "Nominalization in Formal Writing"
                        },
                        new
                        {
                            GrammarTopicId = 103,
                            Description = "Expert Level",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 8,
                            Text = "Discourse Markers"
                        },
                        new
                        {
                            GrammarTopicId = 104,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 9,
                            Text = "Advanced Modals"
                        },
                        new
                        {
                            GrammarTopicId = 105,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 10,
                            Text = "Hedging in Academic Writing"
                        },
                        new
                        {
                            GrammarTopicId = 106,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 11,
                            Text = "Complex Phrasal Verbs"
                        },
                        new
                        {
                            GrammarTopicId = 107,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 12,
                            Text = "Idiomatic Expressions and Collocations"
                        },
                        new
                        {
                            GrammarTopicId = 108,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 13,
                            Text = "Parallelism in Writing"
                        },
                        new
                        {
                            GrammarTopicId = 109,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 14,
                            Text = "Advanced Relative Clauses"
                        },
                        new
                        {
                            GrammarTopicId = 110,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 15,
                            Text = "Degrees of Formality"
                        },
                        new
                        {
                            GrammarTopicId = 111,
                            Description = "Expert Level",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 16,
                            Text = "Complex Sentence Structures"
                        },
                        new
                        {
                            GrammarTopicId = 112,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 17,
                            Text = "Advanced Reporting Verbs"
                        },
                        new
                        {
                            GrammarTopicId = 113,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 18,
                            Text = "Expressing Nuance and Subtlety"
                        },
                        new
                        {
                            GrammarTopicId = 114,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 19,
                            Text = "Advanced Syntax and Structure"
                        },
                        new
                        {
                            GrammarTopicId = 115,
                            Description = "",
                            Explanation = "",
                            LanguageLevelId = 6,
                            Order = 20,
                            Text = "Exploring Regional Variations"
                        });
                });

            modelBuilder.Entity("DbModels.LanguageLevel", b =>
                {
                    b.Property<int>("LanguageLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageLevelId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("LanguageLevelId");

                    b.ToTable("LanguageLevels");

                    b.HasData(
                        new
                        {
                            LanguageLevelId = 1,
                            Code = "A1",
                            Description = "Can understand and use familiar everyday expressions and very basic phrases aimed at the satisfaction of needs of a concrete type.\r\nCan introduce themselves and others and can ask and answer questions about personal details such as where they live, people they know, and things they have.\r\nCan interact in a simple way provided the other person talks slowly and clearly and is prepared to help.",
                            Name = "Beginner",
                            Order = 1
                        },
                        new
                        {
                            LanguageLevelId = 2,
                            Code = "A2",
                            Description = "Can understand sentences and frequently used expressions related to areas of most immediate relevance (e.g., very basic personal and family information, shopping, local geography, employment).\r\nCan communicate in simple and routine tasks requiring a simple and direct exchange of information on familiar and routine matters.\r\nCan describe in simple terms aspects of their background, immediate environment, and matters in areas of immediate need.",
                            Name = "Elementary",
                            Order = 2
                        },
                        new
                        {
                            LanguageLevelId = 3,
                            Code = "B1",
                            Description = "Can understand the main points of clear standard input on familiar matters regularly encountered in work, school, leisure, etc.\r\nCan deal with most situations likely to arise while traveling in an area where the language is spoken.\r\nCan produce simple connected text on topics that are familiar or of personal interest.\r\nCan describe experiences and events, dreams, hopes, and ambitions and briefly give reasons and explanations for opinions and plans.",
                            Name = "Intermediate",
                            Order = 3
                        },
                        new
                        {
                            LanguageLevelId = 4,
                            Code = "B2",
                            Description = "Can understand the main ideas of complex text on both concrete and abstract topics, including technical discussions in their field of specialization.\r\nCan interact with a degree of fluency and spontaneity that makes regular interaction with native speakers quite possible without strain for either party.\r\nCan produce clear, detailed text on a wide range of subjects and explain a viewpoint on a topical issue giving the advantages and disadvantages of various options.",
                            Name = "Upper Intermediate",
                            Order = 4
                        },
                        new
                        {
                            LanguageLevelId = 5,
                            Code = "C1",
                            Description = "Can understand a wide range of demanding, longer texts, and recognize implicit meaning.\r\nCan express ideas fluently and spontaneously without much obvious searching for expressions.\r\nCan use language flexibly and effectively for social, academic, and professional purposes.\r\nCan produce clear, well-structured, detailed text on complex subjects, showing controlled use of organizational patterns, connectors, and cohesive devices.",
                            Name = "Advanced",
                            Order = 5
                        },
                        new
                        {
                            LanguageLevelId = 6,
                            Code = "C2",
                            Description = "Can understand with ease virtually everything heard or read.\r\nCan summarize information from different spoken and written sources, reconstructing arguments and accounts in a coherent presentation.\r\nCan express themselves spontaneously, very fluently and precisely, differentiating finer shades of meaning even in more complex situations.",
                            Name = "Proficiency",
                            Order = 6
                        });
                });

            modelBuilder.Entity("DbModels.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("StoryId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("DbModels.StoryParagraph", b =>
                {
                    b.Property<int>("StoryParagraphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoryParagraphId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranslatedText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StoryParagraphId");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryParagraphs");
                });

            modelBuilder.Entity("DbModels.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "b0834aa8-cbe7-4dfc-ae25-acfea0bf017f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "50a8fe6b-ab4e-47cb-a9cf-15874477c99a",
                            Email = "SuperAdmin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "308245ef-d8c7-401e-b86f-3e882a6e7343",
                            TwoFactorEnabled = false,
                            UserName = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("DbModels.AiMessage", b =>
                {
                    b.HasOne("DbModels.Essay", "Essay")
                        .WithMany("AiMessages")
                        .HasForeignKey("EssayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Essay");
                });

            modelBuilder.Entity("DbModels.GrammarTopic", b =>
                {
                    b.HasOne("DbModels.LanguageLevel", "LanguageLevel")
                        .WithMany()
                        .HasForeignKey("LanguageLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LanguageLevel");
                });

            modelBuilder.Entity("DbModels.StoryParagraph", b =>
                {
                    b.HasOne("DbModels.Story", "Story")
                        .WithMany("Paragraphs")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("DbModels.Essay", b =>
                {
                    b.Navigation("AiMessages");
                });

            modelBuilder.Entity("DbModels.Story", b =>
                {
                    b.Navigation("Paragraphs");
                });
#pragma warning restore 612, 618
        }
    }
}
